### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by reukiodo** [libre-computer-project/libretech-builder-simple#6]
Following the build steps below (replacing BOARD_TARGET)
```
sudo ./setup.sh
git clone --single-branch --depth 1 https://github.com/libre-computer-project/libretech-builder-simple.git
./build.sh aml-s905x-cc
```
but when executing the build script get:
```
+ command -v arm-linux-gnueabihf-gcc
+ echo 'Please install a local armhf toolchain:'
Please install a local armhf toolchain:
+ echo '  $ apt install gcc-arm-linux-gnueabihf'
  $ apt install gcc-arm-linux-gnueabihf
+ exit 1
```
Shouldn't any dependency already be covered in the setup.sh ?

**Comment by reukiodo** [comment]
This is from within the Raspbian build found at https://hub.libre.computer/t/raspbian-11-bullseye-for-libre-computer-boards/82/168

**Comment by dsx724** [comment]
Building from ARM is not supported as some tools are x86 only.

**Comment by reukiodo** [comment]
ah, so I can't build anything from the potato itself?
